In [ ]:
# 2.4、2.5 微积分

In [69]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [70]:
x.requires_grad_(True)
x.grad
print(x.grad)

None


In [71]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [72]:
# import torch
# x = torch.arange(4.0)
# x
# y = 2 * torch.dot(x,x)
# y

In [73]:
# 计算梯度
y.backward(retain_graph=True) 
x.grad

tensor([ 0.,  4.,  8., 12.])

In [74]:
x.grad.zero_()
y = x.sum()

In [75]:
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [76]:
x.grad.zero_()
y = x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [77]:
y.sum().backward()

tensor(14., grad_fn=<SumBackward0>)

In [78]:
x.grad

tensor([0., 0., 0., 0.])

In [82]:
x.grad.zero_()
y = x*x
u = y.detach()
u

tensor([0., 1., 4., 9.])

In [88]:
z = u*x
z,z.sum()

(tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>),
 tensor(36., grad_fn=<SumBackward0>))

In [85]:
z.sum().backward()

In [89]:
x.grad == u

tensor([True, True, True, True])

In [97]:
def f(a):
    b = a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c

a = torch.randn(size=(),requires_grad=True)
# a = torch.tensor(1.,requires_grad=True) 
d = f(a)
d.backward()
a.grad == d/a

tensor(True)

In [96]:
d

tensor(1024., grad_fn=<MulBackward0>)

In [98]:
# 2.6 概率

In [124]:
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

ModuleNotFoundError: No module named 'd2l'

In [105]:
fair_probs = torch.ones([6])/6
multinomial.Multinomial(1,fair_probs).sample()

tensor([0., 1., 0., 0., 0., 0.])

In [106]:
multinomial.Multinomial(10,fair_probs).sample()

tensor([1., 2., 1., 1., 1., 4.])

In [107]:
counts = multinomial.Multinomial(1000,fair_probs).sample()
counts/1000

tensor([0.1690, 0.1680, 0.1600, 0.2020, 0.1700, 0.1310])

In [110]:
multinomial.Multinomial(1000,fair_probs)

Multinomial()

In [112]:
counts = multinomial.Multinomial(10,fair_probs).sample((500,))
counts

tensor([[1., 2., 1., 2., 1., 3.],
        [4., 0., 1., 1., 1., 3.],
        [2., 1., 3., 2., 1., 1.],
        ...,
        [2., 1., 1., 3., 1., 2.],
        [0., 0., 2., 1., 2., 5.],
        [2., 0., 1., 2., 1., 4.]])

In [114]:
counts = multinomial.Multinomial(1,fair_probs).sample((500,))
counts

tensor([[0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0.],
        ...,
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [115]:
counts = multinomial.Multinomial(10,fair_probs).sample((500,))
counts

tensor([[5., 3., 1., 0., 0., 1.],
        [1., 1., 2., 2., 3., 1.],
        [4., 1., 0., 3., 2., 0.],
        ...,
        [2., 3., 0., 4., 1., 0.],
        [2., 2., 2., 1., 2., 1.],
        [1., 1., 2., 4., 2., 0.]])

In [117]:
cum_counts = counts.cumsum(dim=0)
cum_counts

tensor([[  5.,   3.,   1.,   0.,   0.,   1.],
        [  6.,   4.,   3.,   2.,   3.,   2.],
        [ 10.,   5.,   3.,   5.,   5.,   2.],
        ...,
        [815., 825., 830., 848., 824., 838.],
        [817., 827., 832., 849., 826., 839.],
        [818., 828., 834., 853., 828., 839.]])

In [119]:
a = cum_counts.sum(dim=1,keepdims=True)
a

tensor([[  10.],
        [  20.],
        [  30.],
        [  40.],
        [  50.],
        [  60.],
        [  70.],
        [  80.],
        [  90.],
        [ 100.],
        [ 110.],
        [ 120.],
        [ 130.],
        [ 140.],
        [ 150.],
        [ 160.],
        [ 170.],
        [ 180.],
        [ 190.],
        [ 200.],
        [ 210.],
        [ 220.],
        [ 230.],
        [ 240.],
        [ 250.],
        [ 260.],
        [ 270.],
        [ 280.],
        [ 290.],
        [ 300.],
        [ 310.],
        [ 320.],
        [ 330.],
        [ 340.],
        [ 350.],
        [ 360.],
        [ 370.],
        [ 380.],
        [ 390.],
        [ 400.],
        [ 410.],
        [ 420.],
        [ 430.],
        [ 440.],
        [ 450.],
        [ 460.],
        [ 470.],
        [ 480.],
        [ 490.],
        [ 500.],
        [ 510.],
        [ 520.],
        [ 530.],
        [ 540.],
        [ 550.],
        [ 560.],
        [ 570.],
        [ 580.],
        [ 590.

In [122]:
estimates = cum_counts/a
estimates

tensor([[0.5000, 0.3000, 0.1000, 0.0000, 0.0000, 0.1000],
        [0.3000, 0.2000, 0.1500, 0.1000, 0.1500, 0.1000],
        [0.3333, 0.1667, 0.1000, 0.1667, 0.1667, 0.0667],
        ...,
        [0.1637, 0.1657, 0.1667, 0.1703, 0.1655, 0.1683],
        [0.1637, 0.1657, 0.1667, 0.1701, 0.1655, 0.1681],
        [0.1636, 0.1656, 0.1668, 0.1706, 0.1656, 0.1678]])

In [125]:
# d2l.set_figsize((4.5, 3.5))
# d2l.plt.plot(estimates[:, 0], label=("P(coin=heads)"))
# d2l.plt.plot(estimates[:, 1], label=("P(coin=tails)"))
# d2l.plt.axhline(y=0.5, color='black', linestyle='dashed')
# d2l.plt.gca().set_xlabel('Samples')
# d2l.plt.gca().set_ylabel('Estimated probability')
# d2l.plt.legend();