In [95]:
# 背下步骤
# 1.生成数据集
# 2.读取数据集
# 3.定义模型
# 4.初始化模型参数
# 5.定义损失函数
# 6.定义优化算法
# 7.训练（①计算损失，②反向传播，③更新参数）

In [96]:
# 1.生成数据集
import torch
from torch.utils import data
import numpy as np

true_w = torch.tensor([2,-3.4])
true_b = 4.2
features = torch.normal(0,1,(1000,len(true_w)))
labels = (torch.matmul(features,true_w)+true_b).reshape(-1,1)
features,labels

(tensor([[-0.5876, -0.1151],
         [-0.0124,  1.4700],
         [-0.0390, -0.3094],
         ...,
         [ 0.6951, -0.6703],
         [ 0.3493,  0.9729],
         [ 0.2463,  2.5139]]),
 tensor([[ 3.4162e+00],
         [-8.2271e-01],
         [ 5.1742e+00],
         [ 4.9401e+00],
         [ 4.8396e+00],
         [-1.0227e+00],
         [ 3.2134e+00],
         [ 3.6203e+00],
         [ 4.3203e-01],
         [ 1.8749e+00],
         [ 6.0189e+00],
         [ 1.2764e+01],
         [ 4.8263e+00],
         [ 6.4794e-01],
         [ 5.7279e+00],
         [ 8.3948e+00],
         [ 2.7383e+00],
         [ 1.7325e+00],
         [ 9.1660e+00],
         [ 6.8762e+00],
         [ 3.4145e+00],
         [ 9.9375e+00],
         [ 2.0641e+00],
         [ 5.4937e+00],
         [ 4.9472e+00],
         [ 7.1570e-01],
         [-1.7003e+00],
         [ 4.6065e+00],
         [ 1.7018e+00],
         [ 3.4187e+00],
         [ 7.1821e+00],
         [-2.1726e+00],
         [ 4.6491e+00],
         [ 5.7935e

In [97]:
# 2.读取数据集
batch_size = 10
dataset = data.TensorDataset(features,labels)
data_iter = data.DataLoader(dataset,batch_size,shuffle=True)
dataset,dataset[0],data_iter,iter(data_iter)

(<torch.utils.data.dataset.TensorDataset at 0x2066ee29910>,
 (tensor([-0.5876, -0.1151]), tensor([3.4162])),
 <torch.utils.data.dataloader._SingleProcessDataLoaderIter at 0x206725b1e20>)

In [98]:
# 3.定义模型
from torch import nn

net = torch.nn.Sequential(nn.Linear(2,1))

In [99]:
# 4.初始化模型参数
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)
net[0].weight.data,net[0].bias.data,net[0].weight.shape

(tensor([[-0.0072, -0.0051]]), tensor([0.]), torch.Size([1, 2]))

In [100]:
# 5.定义损失函数
loss = nn.MSELoss()
help(nn.MSELoss)

Help on class MSELoss in module torch.nn.modules.loss:

class MSELoss(_Loss)
 |  MSELoss(size_average=None, reduce=None, reduction: str = 'mean') -> None
 |
 |  Creates a criterion that measures the mean squared error (squared L2 norm) between
 |  each element in the input :math:`x` and target :math:`y`.
 |
 |  The unreduced (i.e. with :attr:`reduction` set to ``'none'``) loss can be described as:
 |
 |  .. math::
 |      \ell(x, y) = L = \{l_1,\dots,l_N\}^\top, \quad
 |      l_n = \left( x_n - y_n \right)^2,
 |
 |  where :math:`N` is the batch size. If :attr:`reduction` is not ``'none'``
 |  (default ``'mean'``), then:
 |
 |  .. math::
 |      \ell(x, y) =
 |      \begin{cases}
 |          \operatorname{mean}(L), &  \text{if reduction} = \text{`mean';}\\
 |          \operatorname{sum}(L),  &  \text{if reduction} = \text{`sum'.}
 |      \end{cases}
 |
 |  :math:`x` and :math:`y` are tensors of arbitrary shapes with a total
 |  of :math:`N` elements each.
 |
 |  The mean operation still

In [101]:
# 6.定义优化算法
trainer = torch.optim.SGD(net.parameters(),lr=0.03)
net.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)>

In [102]:
# 7.训练
num_epochs = 3
for epoch in range(num_epochs):  # 在epoch循环下需遍历一次整个数据集
    for X,y in data_iter:  # 采用SGD方法
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features),labels)
    print(f"epoch:{epoch}, loss:{l:.10f}")

epoch:0, loss:0.0001094460
epoch:1, loss:0.0000000009
epoch:2, loss:0.0000000000
