In [20]:
import torch
import torch.nn.functional as F
from torch import nn

In [21]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X-X.mean()

In [22]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [23]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [25]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(-6.9849e-09, grad_fn=<MeanBackward0>)

In [33]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear = torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)

linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 1.1543, -0.1994, -0.0587],
        [-3.0654, -0.3968,  1.2097],
        [-1.0008, -0.5967, -1.1631],
        [ 1.3635,  0.7573, -0.4816],
        [-1.7071, -0.0745,  0.7051]], requires_grad=True)

In [35]:
linear(torch.rand(2,5))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [36]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[6.0602],
        [0.0000]])