In [41]:
import torch
from torch import nn
from torch.nn import functional as F

In [42]:
x = torch.arange(4)
torch.save(x,'x-file')

In [43]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [44]:
y = torch.zeros(4)
torch.save([x,y],'x-files')

In [45]:
x2,y2 = torch.load('x-files')
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [47]:
mydict = {'x':x,'y':y}
torch.save(mydict,'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [48]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2,20))
Y = net(X)

In [52]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.0010,  0.1807,  0.0010,  ..., -0.1179, -0.1968,  0.0096],
                      [ 0.0315,  0.0549, -0.0270,  ...,  0.0657, -0.1242, -0.1109],
                      [ 0.2044, -0.2144, -0.1782,  ...,  0.0328,  0.0439, -0.0265],
                      ...,
                      [ 0.1366,  0.1461,  0.1925,  ...,  0.1817, -0.0154, -0.0351],
                      [-0.1447, -0.2100, -0.1985,  ...,  0.2028,  0.2234,  0.0590],
                      [ 0.1313,  0.0658,  0.0534,  ..., -0.1502, -0.0423,  0.0059]])),
             ('hidden.bias',
              tensor([-1.7510e-02, -1.8887e-01,  1.3593e-01,  2.2006e-01, -6.9782e-02,
                       2.0787e-01, -1.3929e-01, -1.7077e-01, -6.7249e-02,  7.5140e-02,
                      -1.7451e-01, -1.6120e-01, -2.0837e-01, -4.8837e-02,  1.8667e-01,
                      -9.1986e-02,  1.4188e-01, -1.2880e-01,  7.4831e-02, -6.3464e-02,
                      -4.8635e-02,  1.9152e-01,  2.1888e-0

In [54]:
torch.save(net.state_dict(),'mlp.params')

In [55]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [56]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])